name: Sync to GitLab

on:
  push:
    branches:
      - main


jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with: 
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git remote remove gitlab || true
          git remote add gitlab https://${{secrets.GITLAB_USERNAME}}:${{secrets.GITLAB_TOKEN}}@gitlab.tech-labs.dev/michael-maldo/quantengine.git
          git push gitlab main || git push --force gitlab main
